dist: jammy
language: python
python:
- '3.8'
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
install:
- pip install tox python-coveralls
jobs:
  include:
  - stage: flake8
    name: "flake8"
    script: tox -e flake8
  - stage: test
    name: "testSiuSu"
    before_script: tox -e build
    script: tox -e testSiuSu
  - name: "testTsingHap"
    before_script: tox -e build
    script: tox -e testTsingHap
    after_success:
    - coverage report
    - coveralls
  - name: "testDjangoCheckmigration"
    before_script: tox -e build
    script: tox -e checkmigration
  - stage: deploy
    name: "pypi"
    if: branch ~= /\d+\.\d+\.\d+/
    env: TOX_ENV=
    before_script: skip
    script: tox -e build
    deploy:
      provider: pypi
      skip_cleanup: true
      username: __token__
      password: ${PYPI_PASSWORD}
      on:
        tags: true
        distributions: sdist bdist_wheel
