dist: jammy
language: python
python:
- '3.10'
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
install:
- pip install tox
jobs:
  include:
  - stage: flake8
    name: "flake8"
    script: tox -e flake8
  - stage: test
    name: "testSiuSu"
    before_script: tox -e build
    script: tox -e testSiuSu
  - name: "testTsingHap"
    addons:
      # For the `SONARQUBE_SCANNER_PARAMS` variable
      sonarcloud:
        token: ${SONAR_TOKEN}
    before_script: 
    - tox -e build
    - mkdir coverage-reports
    - mv coverage.xml coverage-reports/coverage-build.xml
    script: 
    - tox -e testTsingHap
    - mv coverage.xml coverage-reports/coverage-tsinghap.xml
    - >
      docker run --rm
        -e SONARQUBE_SCANNER_PARAMS
        -e SONAR_TOKEN="${SONAR_TOKEN}"
        -v "`pwd`:/usr/src"
        sonarsource/sonar-scanner-cli
  - name: "testDjangoCheckmigration"
    before_script: tox -e build
    script: tox -e checkmigration
  - stage: deploy
    name: "pypi"
    if: branch ~= /\d+\.\d+\.\d+/
    env: TOX_ENV=
    before_script: skip
    script: tox -e build
    deploy:
      provider: pypi
      skip_cleanup: true
      username: __token__
      password: ${PYPI_PASSWORD}
      on:
        tags: true
        distributions: sdist bdist_wheel
