# Generated by Django 2.1.5 on 2019-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='用字表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('漢字', models.CharField(max_length=5)),
                ('羅馬字', models.CharField(max_length=15)),
                ('分詞', models.CharField(max_length=20)),
            ],
        ),
    ]
