# Generated by Django 2.1.5 on 2019-02-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('用字', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='用字管理表',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': '用字表',
                'verbose_name_plural': '用字表',
            },
            bases=('用字.用字表',),
        ),
    ]
