# Generated by Django 3.2 on 2021-04-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('用字', '0002_用字管理表'),
    ]

    operations = [
        migrations.AlterField(
            model_name='用字表',
            name='分詞',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
