# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('用字', '0003_匯入例句'),
    ]

    operations = [
        migrations.DeleteModel(
            name='用字表',
        ),
    ]
